const options = {
  PRICE_HIGH: "PRICE_DESCENDING",
  PRICE_LOW: "PRICE_ASCENDING",
  MKTCAP_HIGH: "MKT_CAP_DESCENDING",
  MKTCAP_LOW: "MKT_CAP_ASCENDING",
  VOLUME_HIGH: "VOLUME_DESCENDING",
  VOLUME_LOW: "VOLUME_ASCENDING",
  HIGH_24H_HIGH: "HIGH_24H_DESCENDING",
  HIGH_24H_LOW: "HIGH_24H_ASCENDING",
  LOW_24H_HIGH: "LOW_24H_DESCENDING",
  LOW_24H_LOW: "LOW_24H_ASCENDING",
  PERCENT_HIGH: "PERCENT_DESCENDING",
  PERCENT_LOW: "PERCENT_ASCENDING",
  COIN_AZ: "COIN_AZ",
  COIN_ZA: "COIN_ZA",
};

export default options;
